src/pages/main/index.tsx

- css import 방식에서 tailwind방식으로 수정
- 화면 흰색만 나오는 현상 수정 (tailwind로 전환이 미흡했음)

[수정] 메인페이지 컴포넌트 수정

---

src/components/ui/button.tsx
src/components/ui/card.tsx
src/components/ui/input.tsx
src/components/ui/textarea.tsx
src/pages/componentsPage/ComponentsPage.tsx

- ...props 전개연산자가 있으므로, 필수값이 아닌값들은 명시할 필요 없음 => 삭제
- input, button, card, textarea에 접근성 관련 스타일 추가
- 없음

[리팩토링] ui 공통 컴포넌트 props 수정

---

src/components/ui/button.tsx
src/components/ui/card.tsx
src/components/ui/input.tsx
src/components/ui/textField.tsx
src/components/ui/textarea.tsx
src/pages/componentsPage/ComponentsPage.tsx

- 컬러값 사용시 var 대신 tailwind 형식으로 className 사용

[리팩토링] shadcn 컴포넌트에서 tailwind 문법 수정

---

src/api/galaxy.ts
src/components/main/ui/FloatingCTAButton.tsx
src/components/panel/galaxysystems/GalaxySystemCard.tsx
src/components/panel/galaxysystems/GalaxySystemIndex.tsx
src/components/panel/galaxysystems/GalaxySystemList.tsx
src/components/panel/galaxysystems/GalaxySystemSort.tsx
src/hooks/api/useGalaxy.ts
src/mocks/anableMocking.ts
src/mocks/data/galaxies.ts
src/mocks/data/systems.ts
src/mocks/handlers.ts
src/mocks/utils.ts
src/pages/ComponentTestPage.tsx

- GALAXY SYSTEMS 컴포넌트 MSW 페이지네이션 기능 추가
- 메인페이지 -> space페이지 이동 주소 변경

[기능] GALAXY - SYSTEMS 컴포넌트 MSW 페이지네이션 추가

---

src/api/user.ts
src/components/common/TextField.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/EditProfilePanel.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/ProfileView.tsx
src/components/panel/stellar/StellarIndex.tsx
src/hooks/api/useAuth.ts
src/hooks/api/useUser.ts
src/hooks/useChangePassword.ts
src/hooks/useDeactivateAccount.ts
src/hooks/useEditProfile.ts
src/hooks/useLoginForm.ts
src/stores/useUserStore.ts
src/types/user.ts

- 프로필 정보 (username, about) 조회 및 수정 API 연동
- 비밀번호 수정 API 연동
- 회원 탈퇴 연동 API 연동
- 회원 탈퇴 진행 중 비밀번호 형식이 맞지 않을 경우 400에러 발생, 이에 대한 수정 필요
- 회원 탈퇴 레이아웃은 임의로 설정,

[기능] 유저 관련 API 연동

---

src/hooks/api/useAuth.ts

- 401 에러 발생시에도 로컬 상태가 정리되도록 수정
- 토큰 만료된 상태에서도 정상적으로 로그아웃 처리하도록 개선

[수정] 토큰 만료시 로그아웃 401 에러 처리 개선

---

src/types/stellarWrite.ts

- 스텔라 생성 및 수정 api에 보내는 데이터에 position 값 추가함

[리팩토링] 스텔라 생성 및 수정 api의 보내는 데이터에 position 값 추가함

---

src/pages/SpacePage.tsx

- 브리우저 좌우 넓이에 따라 캔버스 크기 조정기능 추가

[수정] 캔버스 좌우 크기에 따라 조절 기능 추가

---

src/api/endpoints.ts
src/api/favorite.ts
src/api/stellar.ts
src/components/layout/Header/SaveButton.tsx
src/components/panel/galaxy/community/CardItem.tsx
src/components/panel/galaxy/community/List.tsx
src/components/panel/galaxy/my/CardItem.tsx
src/components/panel/stellar/info/CloneStellarButton.tsx
src/components/panel/stellar/info/DeleteStellarButton.tsx
src/hooks/api/useStellar.ts
src/types/stellarList.ts

- CloneStellarButton, DeleteStellarButton 컴포넌트 추가
- 스텔라 시스템 클론 및 삭제를 위한 API 엔드포인트와 훅 리팩터링 (파라미터명, 요청 payload 변경 포함)
- 즐겨찾기 API에서 targetId 대신 system_id 사용하도록 수정
- UI 피드백 개선 및 요청 진행 중 버튼 비활성화 처리 추가
- is_liked 속성을 지원하도록 타입과 카드 컴포넌트 업데이트
- 클론 및 삭제 동작은 서버 API 응답 형식에 맞게 검증 필요
- 즐겨찾기 기능 관련 API 변경 사항은 다른 컴포넌트에서도 반영해야 함

[기능] 스텔라 클론/삭제 버튼 추가 및 API·UI 업데이트

---

src/components/panel/stellar/info/StellarInfo.tsx

- StellarInfo에서 로그인된 경우에만 CloneStellarButton이 보이도록 조건 추가
- 비로그인 사용자가 클론 기능에 접근하지 못하도록 제한
- 로그인 상태 확인은 기존 사용자 스토어를 기반으로 처리됨

[리팩토링] 로그인 상태에서만 CLONE 버튼 표시

---

src/api/endpoints.ts
src/api/likes.ts
src/components/common/ButtonLike.tsx
src/components/common/Card/Card.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/LikesPanel.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/ProfileView.tsx
src/components/panel/galaxy/community/CardItem.tsx
src/hooks/api/useLikes.ts
src/types/stellarList.ts
src/utils/likeUtils.ts

- 좋아요 API 연동
- MyLikesPanel 갤럭시 이동
- 프로필 통계 표시
- 타입 안정선 개선 및 유틸리티 분리
- 추후 API 응답 수정 시 like_count 필드 추가

[기능] 좋아요 API 연동

---

src/components/cosmos/Galaxy.tsx
src/components/cosmos/StellarSystem.tsx

- galaxy.tsx 의 StellarSystem컴포넌트 랜더 조건 변경 ( id값 있을때 -> += 모드가 create일때)

[수정] 스텔라 그래픽 랜더 조건 변경

---

src/App.tsx
src/hooks/api/useAuth.ts
src/stores/useUserStore.ts

- 로컬스토리지 기반 토큰 및 사용자 정보 저장으로
새로고침 시 상태 유지

[기능] 새로고침 시 로그인 상태 유지 기능 구현

---

src/components/layout/Sidebar/SidebarNav/SidebarNav.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/LoginPanel.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/OtherUserProfileView.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/ProfileView.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/SignUpPanel.tsx
src/utils/followPanelConfig.ts

- 사용하지 않는 기능 주석처리
- SidebarNav 하단 섹션 (알람, 헬프, 설정)
- 로그인 패널의 비밀번호 찾기
- 로그인, 회원가입 패널 스크롤바 추가
- 한글 메시지들을 영어로 수정

[수정] 사용하지 않는 기능 주석처리 및 UI/UX 개선

---

src/components/cosmos/Galaxy.tsx
src/components/cosmos/LoadingStellarSystem.tsx

- LoadingStellarSystem의 text값 영문으로 변경

[수정] 랜더 로딩 오브젝트 메세지 한글 -> 영어로 수정

---

src/components/cosmos/Planet.tsx

##작업 내용
- Planet 컴포넌트의 color를 useMemo로 관리하도록 변경

[수정] color 데이터 관리 최적화

---

src/pages/SpacePage.tsx

[수정] 불필요 코드 제거

---

src/components/layout/Sidebar/SidebarNav/SidebarNav.tsx
src/hooks/useLoginValidation.ts

[수정] 사용하지 않는 변수들 주석처리 및 삭제

---

src/components/cosmos/Planet.tsx

[수정] 이미지 패스 경로 수정

---

src/components/cosmos/Planet.tsx
src/components/main/canvas/Stars.tsx

'public/assets/Clouds2.png' -> '/assets/Clouds2.png' 변경

[수정] 배포버전 이미지 경로 수정

---

vercel.json

- client 루트 디렉토리에 vercel.json 추가
- vercel 배포 사이트에서 모든 경로를 index.html로 리라이트하도록 설정
- 브라우저에서 /about, /profile 등 직접 접근 시 발생하던 404 문제 해결 (클라이언트 사이드 라우팅 정상 동작)

[빌드] Vercel에서 SPA 리라이트 규칙 추가

---

src/audio/core/AudioEngine.ts
src/audio/core/Planet.ts
src/audio/core/Star.ts
src/audio/core/StellarSystem.ts
src/audio/instruments/DrumInstrument.ts
src/audio/instruments/InstrumentInterface.ts
src/audio/instruments/PadInstrument.ts
src/components/panel/stellar/audioPlayer/Index.tsx
src/components/panel/stellar/audioPlayer/Play.tsx
src/components/panel/stellar/audioPlayer/Volume.tsx
src/hooks/audio/useAudioSync.ts
src/stores/useSelectedStellarStore.ts
src/stores/useStellarStore.ts

This pull request introduces significant improvements to the audio engine and core system for managing playback, transitions, and resource cleanup. The changes enhance the reliability and responsiveness of audio playback, make state management more robust, and add new event subscription APIs for better integration with UI or other systems. The most important changes are grouped below by theme.
**Audio Engine Enhancements**
* Added new transition state management in `AudioEngine`, including `beginTransition`, `endTransition`, and subscription methods, allowing components to react to audio transitions. [[1]](diffhunk://#diff-8072cc206f92158c44b3173a32969de08e4c30f0ee087588fc9e5a90c1a6d37fL15-R22) [[2]](diffhunk://#diff-8072cc206f92158c44b3173a32969de08e4c30f0ee087588fc9e5a90c1a6d37fR182-R329 …

[수정] 오디오 버그 픽스

---

src/hooks/camera/useSmoothCameraMove.ts

- 카메라 애니메이션의 뚝뚝 끊김을 개선하기 위해 보간방식을 변경

[수정] 카메라 애니메이션 보간방식 변경

---

src/components/panel/galaxy/community/List.tsx
src/components/panel/stellar/objects/StellarCard.tsx

- 현재 로그인한 유저 id 와 스텔라시스템의 creator_id가 같을 경우만 노출

[수정] 스텔라 패널 > OBJECSTS 탭 : PLANET 삭제 버튼 노출 조건 변경

---

src/audio/core/AudioEngine.ts
src/audio/core/Planet.ts
src/audio/core/StellarSystem.ts
src/audio/instruments/ArpeggioInstrument.ts
src/audio/instruments/BassInstrument.ts
src/audio/instruments/ChordInstrument.ts
src/audio/instruments/DrumInstrument.ts
src/audio/instruments/MelodyInstrument.ts
src/audio/instruments/PadInstrument.ts
src/components/common/Slider.tsx
src/components/panel/stellar/audioPlayer/Index.tsx
src/components/panel/stellar/audioPlayer/Volume.tsx
src/components/panel/stellar/properties/Gauges.tsx
src/components/panel/stellar/properties/Properties.tsx
src/hooks/audio/useAudioSync.ts
src/stores/useStellarStore.ts
src/types/planetProperties.ts
src/types/starProperties.ts

- masterInput 로직 수정
- 프로퍼티 라벨 변경
- 오디오 볼륨 조정
- 콘솔 로그 제거
- 버그 수정

[리팩토링] 전반적인 오디오 개선

---

src/components/common/PasswordField.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/EditProfilePanel.tsx
src/components/layout/Sidebar/SidebarPanel/Profile/SignUpPanel.tsx
src/hooks/api/useUser.ts
src/hooks/usePasswordValidation.ts

- 프로필 수정 패널에서도 비밀번호 실시간 검증
- 프로필 수정 후 about 필드가 즉시 반영되지 않는 문제 해결

[수정] 프로필 수정 관련 문제 해결

---

src/components/panel/stellar/StellarIndex.tsx

[리팩토링] 스텔라 패널 세로 높이 조절

---

src/components/panel/stellar/info/StellarInfo.tsx
src/stores/useStellarStore.ts

- 스텔라 패널 > INFO : CREATE SOURCE 를 백엔드에서 보내주는 값으로 적용
- 스텔라 패널 : 탭 컨텐츠 높이값 수정

[수정] 추가수정 :  프론트 <-> 백 데이터 매칭

---

src/components/panel/stellar/info/StellarInfo.tsx

- 스텔라 패널 > INFO 글씨 1줄 이상 말줄임표 적용

[수정] 스텔라 패널 > INFO 글씨 1줄 이상 말줄임표 적용

---

src/components/layout/Sidebar/SidebarPanel/Profile/LoginPanel.tsx
src/constants/validationMessages.ts
src/hooks/useChangePassword.ts
src/hooks/usePasswordValidation.ts
src/stores/useStellarStore.ts
src/utils/validation.ts

- setInitialStellarStore 시 create_source_name, original_source_name 값 변경
- 프로필 패널 validation 문구 한글 -> 영어 변경

[리팩토링] validation 문구 영어로 변경 / 스텔라 스토어 init 시 -> create_source_name 저장값 변경

---

src/hooks/api/useAuth.ts
src/hooks/camera/useSmoothCameraMove.ts
src/lib/axios.ts
src/stores/useUserStore.ts

- 현재 프로젝트에선 refresh token 발행 api 없음 -> 프론트 axios 공통 인스턴스에서 refresh 토큰 요청 로직 삭제

[수정] 프로필 컴포넌트 에러 수정

---

src/hooks/api/useAuth.ts
src/lib/axios.ts
src/stores/useUserStore.ts

Reverts SONA-Sound-Orbit-Network-Atlas/client#166

Revert "[수정] 프로필 컴포넌트 에러 수정"

---

src/lib/axios.ts

- axios 공통 인스턴스 파일 내 레거시 코드 삭제

[수정] axios 공통 인스턴스 파일 내 레거시 코드 삭제

---

src/hooks/api/useAuth.ts
src/stores/useUserStore.ts

- jwt access_token 이름 백엔드 기준으로 통일

[수정] jwt access_token 이름 백엔드 기준으로 통일
